version: '3.7'

services:
  web:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8010"
    ports:
      - 8010:8888
    volumes:
      - ./:/code/
      - /home/brian/workspace/:/workspace/
    env_file: .env
    working_dir: /code/
    command: /root/.cache/pypoetry/virtualenvs/codeagi-MATOk_fk-py3.9/bin/jupyter lab --port=8888 --ip=0.0.0.0 --allow-root


